    <h1>Finalizar compra</h1>
<?php if(isset($_SESSION['user'])): ?>
    <a href="<?=base_url?>carrito/index">Ver carrito</a>
    <br/>
    <h3>Direccion de envio:</h3>
    <form action="<?=base_url?>pedido/create" method="post">
        <label for="direccion">Direccion</label>
        <input type="text" name="direccion" required>

        <label for="ciudad">Ciudad</label>
        <input type="text" name="ciudad" required>

        <label for="comuna">Comuna</label>
        <input type="text" name="comuna" required>

        <input type="submit" value="Confirmar pedido">

    </form>
<?php else: ?>
        <p>Identificate para continuar</p>
<?php endif; ?>