<?php if(isset($_SESSION['pedido']) && $_SESSION['pedido']=='Complete'):?>
    <h1>Pedido se a confirmado</h1>
    <p>Tu pedido ha sido guardado con existo, un vez realizada la transferencia a N° 91265467379 con el total del pedido
    , sera procesado y enviado.</p>
    <br>
    <?php if (isset($lastPedido)):?>
    <h3>Datos del pedido:</h3>
        Numero de pedido: v<?=$lastPedido->id?>bsh-01<br>
        Total a pagar:<?=$lastPedido->coste?>$ <br>
        Productos:
        <table>
            <th>Imagen</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Unidades</th>
            <?php while($producto=$detallePedido->fetch_object()) :?>
            <tr>
            <td>
                <?php if ($producto->imagen != null):?>
                    <img src="<?=base_url?>uploads/images/<?=$producto->imagen?>" class="img-carrito" alt="Articulo">
                <?php else :?>
                    <img src="<?=base_url?>assets/img/camiseta.png" class="img-carrito" alt="imagen generica">
                <?php endif;?>
                </td>
                <td><a href="<?=base_url?>producto/product&id=<?=$producto->id?>"><?=$producto->nombre?></a></td>
                <td><?=$producto->precio?></td>
                <td><?=$producto->unidades?></td>
            </tr>
            <?php endwhile; ?>
        </table>
        <a href="<?=base_url?>">Volver al inicio</a>
    <?php endif; ?>
<?php else:?>
    <h1>Pedido no Generado</h1>
    <p>Su pedido no ha sido generado con exito, intente mas tarde</p>
<?php endif;?>