<h1>Detalle del pedido</h1>
<?php if (isset($_SESSION['admin'])):?>
    <h3>Cambiar estado del pedido:</h3>
    <form action="<?=base_url?>pedido/status" method="post">
        <input type="hidden" name="pedido_id" value="<?=$pedido->id?>">
        <select name="estado">
            <option value="confirm" <?=$pedido->estado =='confirm'?'selected':'';?> >Pendiente</option>
            <option value="preparation" <?=$pedido->estado =='preparation'?'selected':'';?> >En preparacion</option>
            <option value="ready" <?=$pedido->estado =='ready'?'selected':'';?> >Preparado para envio</option>
            <option value="sended" <?=$pedido->estado =='sended'?'selected':'';?> >Enviado</option>
        </select>
        <input type="submit" value="Cambiar Estado">
    </form>
    <br>
<?php endif;?>
    <h3>Datos del pedido:</h3>
        Estado: <?=Helper::showstatus($pedido->estado)?><br>
        Numero de pedido: v<?=$pedido->id?>bsh-01<br>
        Total a pagar: <?=$pedido->coste?>$ <br>
        Direccion: <?=$pedido->ciudad?> - <?=$pedido->comuna?> - <?=$pedido->direccion?> <br>
        Productos:
        <table>
            <th>Imagen</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Unidades</th>
            <?php while($producto=$detallePedido->fetch_object()) :?>
            <tr>
            <td>
                <?php if ($producto->imagen != null):?>
                    <img src="<?=base_url?>uploads/images/<?=$producto->imagen?>" class="img-carrito" alt="Articulo">
                <?php else :?>
                    <img src="<?=base_url?>assets/img/camiseta.png" class="img-carrito" alt="imagen generica">
                <?php endif;?>
                </td>
                <td><a href="<?=base_url?>producto/product&id=<?=$producto->id?>"><?=$producto->nombre?></a></td>
                <td><?=$producto->precio?></td>
                <td><?=$producto->unidades?></td>
            </tr>
            <?php endwhile; ?>
        </table>