<h1>Detalle del pedido</h1>
<?php if (isset($_SESSION['admin'])):?>
    <h3>Cambiar detalle del pedido:</h3>
    <form action="" method="post">
        <select name="" id="">
        </select>
    </form>
<?php endif;?>
    <h3>Datos del pedido:</h3>
        Numero de pedido: v<?=$pedido->id?>bsh-01<br>
        Total a pagar: <?=$pedido->coste?>$ <br>
        Direccion: <?=$pedido->ciudad?> - <?=$pedido->comuna?> - <?=$pedido->direccion?> <br>
        Productos:
        <table>
            <th>Imagen</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Unidades</th>
            <?php while($producto=$detallePedido->fetch_object()) :?>
            <tr>
            <td>
                <?php if ($producto->imagen != null):?>
                    <img src="<?=base_url?>uploads/images/<?=$producto->imagen?>" class="img-carrito" alt="Articulo">
                <?php else :?>
                    <img src="<?=base_url?>assets/img/camiseta.png" class="img-carrito" alt="imagen generica">
                <?php endif;?>
                </td>
                <td><a href="<?=base_url?>producto/product&id=<?=$producto->id?>"><?=$producto->nombre?></a></td>
                <td><?=$producto->precio?></td>
                <td><?=$producto->unidades?></td>
            </tr>
            <?php endwhile; ?>
        </table>