<?php if(isset($gestion)):?>
    <h1>Gestionar Pedidos</h1>
<?php else:?>
    <h1>Mis pedidos</h1>
<?php endif;?>
<?php if ($pedidos->num_rows>=1): ?>
<table>
    <th>Id</th>
    <th>Estado</th>
    <th>Coste</th>
    <th>Fecha</th>
    <?php while($pedido=$pedidos->fetch_object()):?>
    <tr>
        <td><a href="<?=base_url?>pedido/detail&id=<?=$pedido->id?>"><?=$pedido->id?></a></td>
        <td>$<?=$pedido->coste?></td>
        <td><?=$pedido->fecha?></td>
        <td><?=$pedido->estado?></td>
    </tr>
    <?php endwhile; ?>
</table>
<?php endif;?>
