<h1>Carrito de la compra</h1>
<?php if(isset($_SESSION['carrito']) && count($carrito)>=1):?>
    <table>
        <th>Imagen</th>
        <th>Nombre</th>
        <th>Precio</th>
        <th>Unidades</th>
        <th>Eliminar</th>
        <?php foreach ($carrito as $indice =>$producto) :?>
        <tr>
            <td>
                <?php if ($producto['producto']->imagen != null):?>
                    <img src="<?=base_url?>uploads/images/<?=$producto['producto']->imagen?>" class="img-carrito" alt="Articulo">
                <?php else :?>
                    <img src="<?=base_url?>assets/img/camiseta.png" class="img-carrito" alt="imagen generica">
                <?php endif;?>
            </td>
            <td><a href="<?=base_url?>producto/product&id=<?=$producto['producto']->id?>" ><?=$producto['producto']->nombre?></a></td>
            <td><?=$producto['producto']->precio?></td>
            <td>
                <a href="<?=base_url?>carrito/up&index=<?=$indice?>" class="button">+</a>
                <?=$producto['unidad']?>
                <a href="<?=base_url?>carrito/down&index=<?=$indice?>" class="button">-</a>
            </td>
            <td><a href="<?=base_url?>carrito/remove&index=<?=$indice?>" class="button button-red">Borrar producto</a></td>
        </tr>
        <?php endforeach; ?>
    </table>
    <br>
    <div class="delete-carrito">
        <a href="<?=base_url?>carrito/delete_all" class="button button-pedido button-red">Borrar Todo</a>
    </div>
    <div class=total-carrito>
        <?php $stats=Helper::statsCarrito();?>
        <h3>Precio total:$<?=$stats['total']?></h3>
        <a href="<?=base_url?>pedido/add" class="button button-pedido" >Comprar</a>
    </div>
<?php else:?>
    <p>Carrito vacio, añade productos para su compra</p>
<?php endif;?>