<?php if(isset($edit) && isset($prod) && is_object($prod)):?>
    <h1>Editar Producto <?=$prod->nombre?></h1>
    <?php $url=base_url."producto/edit&id=".$prod->id;?>
<?php else:?>
    <h1>Crear Nuevo Producto</h1>
    <?php $url=base_url."producto/insert";?>
<?php endif; ?>

<form action="<?=$url?>" method="post" enctype="multipart/form-data">

<label for="nombre">Nombre</label>
<input type="text" name="nombre">

<label for="descripcion">Descripcion</label>
<textarea name="descripcion" cols="30" rows="10"></textarea>

<label for="precio">Precio</label>
<input type="text" name="precio">

<label for="stock">Stock</label>
<input type="number" name="stock">

<label for="categoria">Categoria</label>
<?php $cat=Helper::showCate();?>
<select name="categoria">
    <?php while ($navcat=$cat->fetch_object()):?>
    <option value="<?=$navcat->id?>"><?=$navcat->nombre?></option>
    <?php endwhile;?>
</select>

<label for="imagen">Imagen</label>
<input type="file" name="imagen">

<input type="submit" value="Crear Producto">
</form>