                <h1>Productos destacados</h1>
                <div class="product">
                    <img src="<?=base_url?>assets/img/camiseta.png" alt="Articulo">
                    <h2>Camiseta Azul Holgada</h2>
                    <p>30.000 CLP</p>
                    <a href="" class="button">Añadir al Carro</a>
                </div>
                <div class="product">
                    <img src="<?=base_url?>assets/img/camiseta.png" alt="Articulo">
                    <h2>Camiseta Azul Holgada</h2>
                    <p>30.000 CLP</p>
                    <a href="" class="button">Añadir al Carro</a>
                </div>
                <div class="product">
                    <img src="<?=base_url?>assets/img/camiseta.png" alt="Articulo">
                    <h2>Camiseta Azul Holgada</h2>
                    <p>30.000 CLP</p>
                    <a href="" class="button" >Añadir al Carro</a>
                </div>
                <div class="product">
                    <img src="<?=base_url?>assets/img/camiseta.png" alt="Articulo">
                    <h2>Camiseta Azul Holgada</h2>
                    <p>30.000 CLP</p>
                    <a href="" class="button">Añadir al Carro</a>
                </div>