<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bibrant-ShopCL</title>
    <link rel="stylesheet" href="assets/css/styles.css">
</head>
<body>
    <div id="container">
        <!--Cabecera-->
        <header id="header">
            <div id="logo">
                <img src="assets/img/camiseta.png" alt="LogoDeBibrant-ShopCL">
                <a href="index.php">
                    <h1>Bibrant-ShopCL</h1>
                </a>
            </div>
        </header>
        <!--Menu-->
        <nav id="nav">
            <ul>
                <li><a href="">inicio</a></li>
                <li><a href="">Categoria</a></li>
            </ul>
        </nav>
        <main id="content">