<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bibrant-ShopCL</title>
    <link rel="stylesheet" href="<?=base_url?>assets/css/styles.css">
</head>
<body>
    <div id="container">
        <!--Cabecera-->
        <header id="header">
            <div id="logo">
                <img src="<?=base_url?>assets/img/camiseta.png" alt="LogoDeBibrant-ShopCL">
                <a href="<?=base_url?>">
                    <h1>Bibrant-ShopCl</h1>
                </a>
            </div>
        </header>
        <!--Menu-->
        <?php $cat_nav=Helper::showcate();?>
        <nav id="nav">
            <ul>
                <li><a href="">inicio</a></li>
                <?php while ($nav_cat=$cat_nav->fetch_object()):?>
                <li><a href="<?=base_url?>categoria/read&id=<?=$nav_cat->id?>"><?=$nav_cat->nombre?></a></li>
                <?php endwhile;?>
            </ul>
        </nav>
        <main id="content">