<!--BarraLateral-->
            <aside id="aside">
                <div class="block-aside" id="login">
                    <?php if (!isset($_SESSION['user'])):?>
                    <h3>Entrar a la web</h3>
                    <?=isset($_SESSION['login'])?'<strong>'.$_SESSION['login'].'</strong>':''?>
                    <form action="<?=base_url?>usuario/login" method="post">
                        <label for="email">Email</label>
                        <input type="email" name="email">
                        <label for="pass">Contraseña</label>
                        <input type="password" name="pass">
                        <input type="submit" value="Enviar">
                    </form>
                    <a href="<?=base_url?>usuario/register">Registrarse</a>
                    <?php else:?>
                        <h3><?=$_SESSION['user']->nombre?> <?=$_SESSION['user']->apellidos?></h3>
                        <ul>
                            <?php if(isset($_SESSION['admin'])):?>
                            <li><a href="<?=base_url?>categoria/index">Gestinar Categorias</a></li>
                            <li><a href="">Gestinar Productos</a></li>
                            <li><a href="">Gestinar Pedidos</a></li>
                            <?php endif; ?>
                            <li><a href="">Mis pedidos</a></li>
                            <li><a href="<?=base_url?>usuario/logout">Cerrar sesion</a></li>
                        </ul>
                    <?php endif;?>
                    <?php Helper::deleteSession('login'); ?>
                </div>
            </aside>
            <!--Contenido Principal-->
            <section id="main">