<!--BarraLateral-->
            <aside id="aside">
                <div class="block-aside" id="login">
                    <h3>Entrar a la web</h3>
                    <form action="" method="post">
                        <label for="email">Email</label>
                        <input type="email" name="email">
                        <label for="pass">Contraseña</label>
                        <input type="password" name="pass">
                        <input type="submit" value="Enviar">
                    </form>
                    <ul>
                        <li><a href="">Mis pedidos</a></li>
                        <li><a href="">Gestinar pedidos</a></li>
                        <li><a href="">gestinar Categorias</a></li>
                    </ul>
                </div>
            </aside>
            <!--Contenido Principal-->
            <section id="main">