<h1>Registrarse</h1>
<?php
if (isset($_SESSION['registro'])):?>
    <strong><?=$_SESSION['registro']?></strong>
<?php endif;?>
<?php Helper::deleteSession('registro'); ?>
<form action="<?=base_url?>usuario/insert" method="POST">
    <label for="nombre">Nombre</label>
    <input type="text" name="nombre" required>

    <label for="apellidos">Apellidos</label>
    <input type="text" name="apellidos" required>

    <label for="email">Email</label>
    <input type="email" name="email" required>

    <label for="pass">Contraseña</label>
    <input type="password" name="pass" required>
    <input type="submit" value="Registrarse">
</form>